version: '2'

services:
  ui:
    image: nginx:latest
    restart: always
    environment:
      DBPROXY_HOST: "dbproxy"
      DBPROXY_PORT: 8000
      PROXY: "http://dbproxy:8000"
    volumes:
      - "$PWD/UI/uicode/build/:/usr/share/nginx/html:ro"
      - "$PWD/UI/uiconf/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8080:80"
    depends_on: 
      - couchdb
      - dbproxy
    networks:
      senetwork:
        aliases:
          - ui

