version: '2'

services:
  getimagefromurl:
    build: ./GetImageFromURL
    image: searchengine-getimagefromurl:0.2.5
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "$PWD/GetImageFromURL/tmp:/tmp"
    networks:
      senetwork:
        aliases:
          - getimagefromurl

  getcontentfromurl:
    build: ./GetContentFromURL
    image: searchengine-getcontentfromurl:0.0.7
    restart: always
    ports:
      - "6000:6000"
    volumes:
      - "$PWD/GetContentFromURL/tmp:/tmp"
    networks:
      senetwork:
        aliases:
          - getcontentfromurl

  saveurlintodb:
      build: ./SaveUrlIntoDB    
      environment: 
        COUCHDB_HOST: "couchdb"        
        CONTENT_HOST: "getcontentfromurl"      
      ports:
        - "6001:6001"    
      depends_on: 
        - couchdb
        - couchdb-lucene
        - getcontentfromurl
      networks:
        senetwork:
          aliases:
            - saveurlintodb
  gethashfromurl:
    build: ./GetHashFromURL
    image: searchengine-gethashfromurl:0.0.2
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "$PWD/GetHashFromURL/tmp:/tmp"
    networks:
      senetwork:
        aliases:
          - gethashfromurl

  couchdb:
    build:
      context: ./CouchDBLucene/
      dockerfile: ./Dockerfile-couchdb
    image: searchengine-couchdb:0.0.1
    ports:
      - "5984:5984"
    networks:
      senetwork:
        aliases:
          - couchdb

  couchdb-lucene:
    image: klaemo/couchdb-lucene:latest
    networks:
      senetwork:
        aliases:
          - couchdb-lucene

networks:
  senetwork:
    driver: bridge
