version: '2'

services:
  databaseinit:
    build: ./DatabaseInit
    image: searchengine-databaseinit:0.0.2
    volumes:
      - "$PWD/DatabaseInit/dbinitstatus:/dbinitstatus"
    environment:
      COUCHDB_HOST: "couchdb"
    depends_on: 
      - couchdb
    networks:
      senetwork:
        aliases:
          - databaseinit

  ui:
    build: ./SearchEngineUI
    image: searchengine-ui:0.0.11
    restart: always
    environment:
      COUCHDB_HOST: "couchdb"
      DBPROXY_HOST: "dbproxy"
    ports:
      - "8080:8080"
    depends_on: 
      - couchdb
      - dbproxy
    networks:
      senetwork:
        aliases:
          - ui

  getimagefromurl:
    build: ./GetImageFromURL
    image: searchengine-getimagefromurl:0.2.5
    restart: always
    volumes:
      - "$PWD/GetImageFromURL/tmp:/tmp"
    networks:
      senetwork:
        aliases:
          - getimagefromurl

  getcontentfromurl:
    build: ./GetContentFromURL
    image: searchengine-getcontentfromurl:0.0.7
    restart: always
    volumes:
      - "$PWD/GetContentFromURL/tmp:/tmp"
    networks:
      senetwork:
        aliases:
          - getcontentfromurl

  dbproxy:
    build: ./DBProxy
    image: searchengine-dbproxy:0.0.3
    restart: always
    environment:
      COUCHDB_HOST: "couchdb"
      IMAGE_HOST: "getimagefromurl"
      CONTENT_HOST: "getcontentfromurl"
    ports:
      - "8000:8000"
    depends_on: 
      - couchdb
      - couchdb-lucene
      - getcontentfromurl
      - getimagefromurl
    networks:
      senetwork:
        aliases:
          - dbproxy

  couchdb:
    build:
      context: ./CouchDBLucene/
      dockerfile: ./Dockerfile-couchdb
    restart: always
    volumes:
      - "$PWD/data:/opt/couchdb/data"
    networks:
      senetwork:
        aliases:
          - couchdb

  couchdb-lucene:
    image: klaemo/couchdb-lucene:latest
    restart: always
    networks:
      senetwork:
        aliases:
          - couchdb-lucene

networks:
  senetwork:
    driver: bridge
