version: '2'

services:
  getimagefromurl:
    ports:
      - "3000:3000"

  getcontentfromurl:
    ports:
      - "6000:6000"

  dbproxy:
    ports:
      - "8000:8000"

  couchdb:
    ports:
      - "5984:5984"
